# Generated by Django 5.0.7 on 2024-07-13 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewTitle', models.CharField(max_length=100)),
                ('ReviewMessage', models.TextField(max_length=500)),
                ('ReviewImage', models.ImageField(upload_to='static')),
                ('Upload_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Type', models.CharField(choices=[('AN', 'Anime'), ('TW', 'TV/WebSeries'), ('MV', 'Movie')], default='AN', max_length=2)),
                ('ReviewUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
