# Generated by Django 5.0.7 on 2024-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App', '0002_alter_reviewmodel_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ReviewImage',
            field=models.ImageField(upload_to='static'),
        ),
    ]
