# Generated by Django 5.0.7 on 2024-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App', '0003_alter_reviewmodel_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ReviewImage',
            field=models.CharField(max_length=1000),
        ),
    ]
