# Generated by Django 5.0.7 on 2024-10-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App', '0004_alter_reviewmodel_reviewimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='ReviewImage',
            new_name='ReviewImageURL',
        ),
    ]
